on:
  pull_request:
    branches:
    - main
    - 'release/**'
    - 'cicd/**'
    - dev
  workflow_call:
  
jobs:
  test:
    name: Test bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test codebase
        run: go test -v ./...
      - name: Check codebase builds successfully
        run: go build -v ./...